#ifndef DAYS_OF_WEEK_H__
#define DAYS_OF_WEEK_H__

#define SUNDAY		0
#define MONDAY		1
#define TUESDAY		2
#define WEDNESDAY	3
#define THURSDAY	4
#define FRIDAY		5
#define SATURDAY	6

#define SUNDAY_M	(1 << SUNDAY)
#define MONDAY_M	(1 << MONDAY)
#define TUESDAY_M	(1 << TUESDAY)
#define WEDNESDAY_M	(1 << WEDNESDAY)
#define THURSDAY_M	(1 << THURSDAY)
#define FRIDAY_M	(1 << FRIDAY)
#define SATURDAY_M	(1 << SATURDAY)

#define WEEKDAYS_M	(MONDAY_M|TUESDAY_M|WEDNESDAY_M|THURSDAY_M|FRIDAY_M)
#define WEEKEND_M	(SATURDAY_M|SUNDAY_M)
#define ALL_DAYS_M	(MONDAY_M|TUESDAY_M|WEDNESDAY_M|THURSDAY_M|FRIDAY_M|SATURDAY_M|SUNDAY_M)

#endif /* DAYS_OF_WEEK_H__ */
