name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rnascunha/agro_container:v5.0
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Prepare
        run: |
           cp sdkconfig-action sdkconfig
      - name: Building
        run: |
          idf.py build