name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: rnascunha/agro_container:v5.0
      env:
        IDF_PATH: /opt/esp/idf
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Prepare
        run: |
          cp sdkconfig-action sdkconfig
      - name: Exporting IDF & Building
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build