#ifndef AGRO_MESH_SENSOR_TYPE_LIST_HPP__
#define AGRO_MESH_SENSOR_TYPE_LIST_HPP__

#define SENSOR_TYPE_RSSI		1
#define SENSOR_TYPE_TEMP		2
#define SENSOR_TYPE_GPIOS		5

#endif /* AGRO_MESH_SENSOR_TYPE_LIST_HPP__ */
